### ISSUE TITLE
Incorrect number of parameters for function openPDF

### ISSUE THREAD

**Issue by andersdp** [DaveKun/TiPDF#1]
Hi - not a lot of activity on this module, hope to get an answer 🙂

Whenever I do:
tiPDF.openPDF(newFile.nativePath);

I get an "Incorrect number of parameters for function openPDF" error?

**Comment by DaveMcMartin** [comment]
Hello, I'm going to fix it this week

**Comment by DaveMcMartin** [comment]
Version 2.3.2 was released, it contains a fix for this bug.

**Comment by andersdp** [comment]
Thanks - it works 👍🏼
